In [1]:
import numpy as np
import pandas as pd

In [6]:
A = pd.DataFrame({"c1":[1,0,-1],"c2":[1,1,1]})
display(A)

c1  c2
0   1   1
1   0   1
2  -1   1

In [9]:
A.T

0  1  2
c1  1  0 -1
c2  1  1  1

In [11]:
A2=np.dot(A.T,A)
display(A2)

array([[2, 0],
       [0, 3]], dtype=int64)

In [15]:
np.linalg.eigvals(A2)

array([2., 3.])

In [16]:
np.linalg.eig(A2)

(array([2., 3.]),
 array([[1., 0.],
        [0., 1.]]))

In [21]:
test=pd.DataFrame({'a':[3,4],'b':[0,5]})
test

a  b
0  3  0
1  4  5

In [22]:
np.linalg.svd(test)

(array([[-0.31622777, -0.9486833 ],
        [-0.9486833 ,  0.31622777]]),
 array([6.70820393, 2.23606798]),
 array([[-0.70710678, -0.70710678],
        [-0.70710678,  0.70710678]]))

In [23]:
3*(5)**0.5

6.708203932499369

In [24]:
5**0.5

2.23606797749979

In [25]:
1/(2**0.5)

0.7071067811865475

In [26]:
1/(10**0.5)

0.31622776601683794